FROM node
ADD entrypoint-node.sh /entrypoint-node.sh
RUN chmod +x entrypoint-node.sh
EXPOSE 3000
RUN groupadd informatica -g$GID
RUN adduser --disabled-password --uid $UID --gid $GID --gecos "" informatica
USER informatica
WORKDIR /app
CMD ["/entrypoint-node.sh"]
