FROM node
ADD entrypoint-node.sh /entrypoint-node.sh
RUN chmod +x entrypoint-node.sh
EXPOSE 3000
RUN groupadd informatica -g1001
RUN adduser --disabled-password --uid 1001 --gid 1001 --gecos "" informatica
USER informatica
WORKDIR /app
CMD ["/entrypoint-node.sh"]
